import type { Metadata } from "next";
import TopBar from "@/components/TopBar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Terms of Service — Character AI",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen">
      <TopBar />
      <main id="main" className="mx-auto max-w-3xl px-4 py-10">
        <article className="prose-legal">
          <h1 className="text-3xl font-bold text-white">Terms of Service</h1>
          <p className="mt-2 text-sm text-muted">Last updated: {new Date().getFullYear()}</p>

          <Section title="1. Acceptance of terms">
            By accessing or using Character AI (the &ldquo;Service&rdquo;) you
            agree to be bound by these Terms. If you do not agree, do not use the
            Service.
          </Section>

          <Section title="2. Eligibility & age">
            You must be at least 18 years old to use the Service. By using it you
            represent that you meet this requirement. We may restrict or terminate
            access where age or identity cannot be reasonably assured.
          </Section>

          <Section title="3. Your account">
            You are responsible for the activity under your account and for
            keeping your credentials secure. Notify us immediately of any
            unauthorised use. You may delete your account at any time from{" "}
            <a href="/settings" className="text-brand-soft hover:underline">
              account settings
            </a>
            .
          </Section>

          <Section title="4. User-generated content">
            You may create characters and other content. You retain ownership of
            what you create, and you grant us a licence to host, display and
            process it to operate the Service. You are solely responsible for
            content you submit and represent that you have the rights to it.
          </Section>

          <Section title="5. Prohibited content & conduct">
            You must not create, share, or solicit content that:
            <ul className="mt-2 list-disc space-y-1 pl-6">
              <li>
                sexualises minors or depicts child sexual abuse in any form
                (this is strictly prohibited and reported to authorities);
              </li>
              <li>is unlawful, harassing, hateful, or incites violence;</li>
              <li>impersonates real people in a deceptive or harmful way;</li>
              <li>infringes intellectual property or privacy rights;</li>
              <li>contains malware, spam, or attempts to disrupt the Service.</li>
            </ul>
            We use automated screening and human review, and may remove content
            or suspend accounts that violate these rules.
          </Section>

          <Section title="6. AI-generated output">
            Character responses are generated by AI and may be inaccurate,
            offensive, or otherwise inappropriate. Output does not represent our
            views. Do not rely on it for professional, legal, medical, or
            financial advice.
          </Section>

          <Section title="7. Reporting">
            You can report content that violates these Terms using the report
            control available throughout the Service. We review reports and act
            where appropriate.
          </Section>

          <Section title="8. Termination">
            We may suspend or terminate access for violations of these Terms or
            to comply with the law. You may stop using the Service at any time.
          </Section>

          <Section title="9. Disclaimers & liability">
            The Service is provided &ldquo;as is&rdquo; without warranties of any
            kind. To the maximum extent permitted by law, we are not liable for
            indirect or consequential damages arising from your use of the
            Service.
          </Section>

          <Section title="10. Changes">
            We may update these Terms. Material changes will be posted here with a
            revised date. Continued use after changes constitutes acceptance.
          </Section>

          <Section title="11. Contact">
            Questions about these Terms can be sent to the operator of this
            deployment.
          </Section>

          <p className="mt-8 rounded-lg border border-line bg-bg-soft p-4 text-xs text-muted">
            This document is a template provided with the open-source project and
            is not legal advice. Operators should have it reviewed by a qualified
            lawyer for their jurisdiction before launch.
          </p>
        </article>
      </main>
      <Footer />
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-6">
      <h2 className="text-lg font-semibold text-white">{title}</h2>
      <div className="mt-2 text-sm leading-relaxed text-muted">{children}</div>
    </section>
  );
}
